package com.citylogic.domain.tick;

import com.citylogic.domain.buildings.BuildingDescription;
import com.citylogic.domain.buildings.IBuildingState;
import com.citylogic.domain.core.CitySnapshot;
import com.citylogic.domain.core.ResourceDelta;
import com.citylogic.domain.map.IGridReadPort;

import java.util.List;

/**
 * Production Phase: distributes electrical energy from utility generators (e.g. Solar Plants)
 * to consumers (Houses, Commercial, Factories).
 * Applies economic & demographic yields for powered buildings.
 * When houses lack access to energy, a direct satisfaction/happiness penalty is applied.
 */
public class ProductionPhase implements ITickPhase {
    /**
     * Happiness penalty applied per tick for each residential house without access to electricity.
     */
    public static final double UNPOWERED_HOUSE_HAPPINESS_PENALTY = -2.5;

    @Override
    public ResourceDelta execute(CitySnapshot snapshot, IGridReadPort grid) {
        List<IBuildingState> buildings = grid.getAllBuildings();

        // 1. Calculate available clean energy generated by active power facilities (e.g. Solar Plants)
        int availableEnergy = 0;
        for (IBuildingState b : buildings) {
            if (b.isManualShutdown()) {
                b.setPowered(false);
                continue;
            }
            if (b.getEnergyProduction() > 0) {
                availableEnergy += b.getEnergyProduction();
                b.setPowered(true);
            }
        }

        // 2. Distribute power to consumers.
        // Priority 1: Residential homes (citizens require lighting, heating, power to be satisfied)
        int remainingEnergy = availableEnergy;
        for (IBuildingState b : buildings) {
            if (b.getDescription().getCategory() == BuildingDescription.Category.RESIDENTIAL) {
                if (b.isManualShutdown()) {
                    b.setPowered(false);
                    continue;
                }
                int demand = b.getEnergyConsumption();
                if (demand > 0) {
                    if (remainingEnergy >= demand) {
                        b.setPowered(true);
                        remainingEnergy -= demand;
                    } else {
                        // Not enough power capacity: blackout for this house
                        b.setPowered(false);
                    }
                } else {
                    b.setPowered(true);
                }
            }
        }

        // Priority 2: Commercial and Industrial facilities
        for (IBuildingState b : buildings) {
            BuildingDescription.Category cat = b.getDescription().getCategory();
            if (cat != BuildingDescription.Category.RESIDENTIAL && cat != BuildingDescription.Category.UTILITY) {
                if (b.isManualShutdown()) {
                    b.setPowered(false);
                    continue;
                }
                int demand = b.getEnergyConsumption();
                if (demand > 0) {
                    if (remainingEnergy >= demand) {
                        b.setPowered(true);
                        remainingEnergy -= demand;
                    } else {
                        b.setPowered(false);
                    }
                } else {
                    b.setPowered(true);
                }
            }
        }

        // 3. Aggregate production and apply unpowered residential penalties
        ResourceDelta total = ResourceDelta.zero();

        for (IBuildingState building : buildings) {
            if (building.isPowered()) {
                total = total.merge(building.getBaseProduction());
            } else {
                // If a residential house does not have access to energy, citizen satisfaction drops!
                if (building.getDescription().getCategory() == BuildingDescription.Category.RESIDENTIAL) {
                    total = total.merge(new ResourceDelta(0.0, 0.0, 0, UNPOWERED_HOUSE_HAPPINESS_PENALTY));
                }
            }
        }

        return total;
    }
}
